version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: user_management_postgres
    environment:
      POSTGRES_DB: user_management_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - teamsync_network

  user-management-service:
    build: .
    container_name: user_management_service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_management_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - teamsync_network

volumes:
  postgres_data:

networks:
  teamsync_network:
    external:
      name: teamsync_network