# API Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: teamsync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: prithuanan/teamsync-api-gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: AUTH_SERVICE_URL
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: USER_SERVICE_URL
        - name: PROJECT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: PROJECT_SERVICE_URL
        - name: TASK_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: TASK_SERVICE_URL
        - name: MESSAGE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: MESSAGE_SERVICE_URL
        - name: FEED_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: FEED_SERVICE_URL
        - name: AI_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: AI_BACKEND_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: teamsync
spec:
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001  # Add this line
  type: NodePort     # Change from LoadBalancer to NodePort