apiVersion: v1
kind: ConfigMap
metadata:
  name: teamsync-config
  namespace: teamsync
data:
  # Database configurations
  AUTH_DB_URL: "jdbc:postgresql://auth-postgres:5432/auth-db"
  USER_DB_URL: "jdbc:postgresql://user-postgres:5432/user_management_db"
  PROJECT_DB_URL: "jdbc:postgresql://project-postgres:5432/project_management_db"
  TASK_DB_URL: "jdbc:postgresql://task-postgres:5432/task_management_db"
  FEED_DB_URL: "jdbc:postgresql://feed-postgres:5432/feed_management_db"
  MESSAGE_DB_URL: "jdbc:postgresql://message-postgres:5432/message_management_db"
  
  # Kafka configuration
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  
  # Service URLs
  AUTH_SERVICE_URL: "http://auth-service:8081"
  USER_SERVICE_URL: "http://user-management-service:8082"
  PROJECT_SERVICE_URL: "http://project-management-service:8083"
  TASK_SERVICE_URL: "http://task-management-service:8089"
  FEED_SERVICE_URL: "http://feed-management-service:8090"
  MESSAGE_SERVICE_URL: "http://message-management-service:8091"
  AI_BACKEND_URL: "http://ai-backend:8000"
  