# Auth Database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-postgres
  namespace: teamsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres
  template:
    metadata:
      labels:
        app: auth-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "auth-db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: postgres-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: auth-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: auth-postgres
  namespace: teamsync
spec:
  selector:
    app: auth-postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-postgres-pvc
  namespace: teamsync
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# User Database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-postgres
  namespace: teamsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-postgres
  template:
    metadata:
      labels:
        app: user-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "user_management_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: postgres-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: user-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-postgres
  namespace: teamsync
spec:
  selector:
    app: user-postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-postgres-pvc
  namespace: teamsync
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Project Database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-postgres
  namespace: teamsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-postgres
  template:
    metadata:
      labels:
        app: project-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "project_management_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: postgres-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: project-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: project-postgres
  namespace: teamsync
spec:
  selector:
    app: project-postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-postgres-pvc
  namespace: teamsync
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Task Database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-postgres
  namespace: teamsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-postgres
  template:
    metadata:
      labels:
        app: task-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "task_management_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: postgres-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: task-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: task-postgres
  namespace: teamsync
spec:
  selector:
    app: task-postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-postgres-pvc
  namespace: teamsync
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Message Database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-postgres
  namespace: teamsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-postgres
  template:
    metadata:
      labels:
        app: message-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "message_management_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: postgres-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: message-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: message-postgres
  namespace: teamsync
spec:
  selector:
    app: message-postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: message-postgres-pvc
  namespace: teamsync
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Feed Database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-postgres
  namespace: teamsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-postgres
  template:
    metadata:
      labels:
        app: feed-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "feed_management_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: postgres-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: feed-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: feed-postgres
  namespace: teamsync
spec:
  selector:
    app: feed-postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: feed-postgres-pvc
  namespace: teamsync
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi