# Auth Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: teamsync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      initContainers:
      - name: flyway-migration
        image: flyway/flyway:latest
        command: ['flyway', 'migrate', '-url=jdbc:postgresql://auth-postgres:5432/auth-db', '-user=postgres', '-password=postgres', '-locations=filesystem:/flyway/sql']
        volumeMounts:
        - name: migration-files
          mountPath: /flyway/sql
      volumes:
      - name: migration-files
        configMap:
          name: auth-migration-files
      containers:
      - name: auth-service
        image: prithuanan/teamsync-auth:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: AUTH_DB_URL
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: postgres-password
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: USER_SERVICE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: teamsync
spec:
  selector:
    app: auth-service
  ports:
  - port: 8081
    targetPort: 8081
---
# User Management Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-service
  namespace: teamsync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-management-service
  template:
    metadata:
      labels:
        app: user-management-service
    spec:
      initContainers:
      - name: flyway-migration
        image: flyway/flyway:latest
        command: ['flyway', 'migrate', '-url=jdbc:postgresql://user-postgres:5432/user_management_db', '-user=postgres', '-password=postgres', '-locations=filesystem:/flyway/sql']
        volumeMounts:
        - name: migration-files
          mountPath: /flyway/sql
      volumes:
      - name: migration-files
        configMap:
          name: user-migration-files
      containers:
      - name: user-management-service
        image: prithuanan/teamsync-user:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: USER_DB_URL
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: postgres-password
        - name: PROJECT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: PROJECT_SERVICE_URL
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: SCHEMA_REGISTRY_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  namespace: teamsync
spec:
  selector:
    app: user-management-service
  ports:
  - port: 8082
    targetPort: 8082
---
# Project Management Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-management-service
  namespace: teamsync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-management-service
  template:
    metadata:
      labels:
        app: project-management-service
    spec:
      initContainers:
      - name: flyway-migration
        image: flyway/flyway:latest
        command: ['flyway', 'migrate', '-url=jdbc:postgresql://project-postgres:5432/project_management_db', '-user=postgres', '-password=postgres', '-locations=filesystem:/flyway/sql']
        volumeMounts:
        - name: migration-files
          mountPath: /flyway/sql
      volumes:
      - name: migration-files
        configMap:
          name: project-migration-files
      containers:
      - name: project-management-service
        image: prithuanan/teamsync-project:latest
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: PROJECT_DB_URL
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: postgres-password
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: USER_SERVICE_URL
        - name: TASK_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: TASK_SERVICE_URL
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: SCHEMA_REGISTRY_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: project-management-service
  namespace: teamsync
spec:
  selector:
    app: project-management-service
  ports:
  - port: 8083
    targetPort: 8083
---
# Task Management Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management-service
  namespace: teamsync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-management-service
  template:
    metadata:
      labels:
        app: task-management-service
    spec:
      initContainers:
      - name: flyway-migration
        image: flyway/flyway:latest
        command: ['flyway', 'migrate', '-url=jdbc:postgresql://task-postgres:5432/task_management_db', '-user=postgres', '-password=postgres', '-locations=filesystem:/flyway/sql']
        volumeMounts:
        - name: migration-files
          mountPath: /flyway/sql
      volumes:
      - name: migration-files
        configMap:
          name: task-migration-files
      containers:
      - name: task-management-service
        image: prithuanan/teamsync-task:latest
        ports:
        - containerPort: 8089
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: TASK_DB_URL
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: postgres-password
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: USER_SERVICE_URL
        - name: PROJECT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: PROJECT_SERVICE_URL
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: SCHEMA_REGISTRY_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8089
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8089
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: task-management-service
  namespace: teamsync
spec:
  selector:
    app: task-management-service
  ports:
  - port: 8089
    targetPort: 8089
---
# Message Management Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-management-service
  namespace: teamsync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message-management-service
  template:
    metadata:
      labels:
        app: message-management-service
    spec:
      initContainers:
      - name: flyway-migration
        image: flyway/flyway:latest
        command: ['flyway', 'migrate', '-url=jdbc:postgresql://message-postgres:5432/message_management_db', '-user=postgres', '-password=postgres', '-locations=filesystem:/flyway/sql']
        volumeMounts:
        - name: migration-files
          mountPath: /flyway/sql
      volumes:
      - name: migration-files
        configMap:
          name: message-migration-files
      containers:
      - name: message-management-service
        image: prithuanan/teamsync-message:latest
        ports:
        - containerPort: 8091
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: MESSAGE_DB_URL
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: postgres-password
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: USER_SERVICE_URL
        - name: PROJECT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: PROJECT_SERVICE_URL
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: SCHEMA_REGISTRY_URL
        - name: AZURE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: azure-connection-string
        - name: AZURE_CONTAINER_NAME
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: azure-container-name
        - name: AZURE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: azure-account-name
        - name: AZURE_SAS_TOKEN
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: azure-sas-token
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8091
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8091
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: message-management-service
  namespace: teamsync
spec:
  selector:
    app: message-management-service
  ports:
  - port: 8091
    targetPort: 8091
---
# Feed Management Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-management-service
  namespace: teamsync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed-management-service
  template:
    metadata:
      labels:
        app: feed-management-service
    spec:
      initContainers:
      - name: flyway-migration
        image: flyway/flyway:latest
        command: ['flyway', 'migrate', '-url=jdbc:postgresql://feed-postgres:5432/feed_management_db', '-user=postgres', '-password=postgres', '-locations=filesystem:/flyway/sql']
        volumeMounts:
        - name: migration-files
          mountPath: /flyway/sql
      volumes:
      - name: migration-files
        configMap:
          name: feed-migration-files
      containers:
      - name: feed-management-service
        image: prithuanan/teamsync-feed:latest
        ports:
        - containerPort: 8090
        env:
        # In the feed-management-service deployment, add these environment variables:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: FEED_DB_URL
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: postgres-password
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL
          valueFrom:
            configMapKeyRef:
              name: teamsync-config
              key: SCHEMA_REGISTRY_URL
        - name: AZURE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: azure-connection-string
        - name: AZURE_CONTAINER_NAME
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: azure-container-name
        - name: AZURE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: azure-account-name
        - name: AZURE_SAS_TOKEN
          valueFrom:
            secretKeyRef:
              name: teamsync-secrets
              key: azure-sas-token
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: feed-management-service
  namespace: teamsync
spec:
  selector:
    app: feed-management-service
  ports:
  - port: 8090
    targetPort: 8090
