version: '3.8'

services:
  auth-postgres:
    image: postgres:15
    container_name: auth_postgres
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - teamsync_network

  auth-service:
    build: .
    container_name: auth_service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-postgres:5432/auth-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - auth-postgres
    networks:
      - teamsync_network

volumes:
  postgres_data:

networks:
  teamsync_network:
    external: true