services:
  ai-backend:
    image: teamsync-ai-backend:latest
    build: .
    env_file:
      - .env
    volumes:
      - ./firebase-creds.json:/app/firebase-creds.json:ro
    ports:
      - "8000:8000"
    networks:
      - teamsync_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  teamsync_network:
    external: true
