version: '3.8'
services:
  frontend:
    image: prithuanan/teamsync-social-flow:${TAG:-latest}
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - teamsync_network

    healthcheck:
      test: ["CMD-SHELL",
        "curl -fsS http://api-gateway:8080/api/health || exit 1 && \
         curl -fsS http://135.235.169.115:8000/health || exit 1"
      ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  teamsync_network:
    external: true
